### ISSUE TITLE
The license is not included in the repo and the link provided does not point to it.

### ISSUE THREAD

**Issue by blmt** [nanoporetech/pyguppyclient#1]
I tried to follow the link to download the:
 Oxford Nanopore Technologies, Ltd. Public License, v1.0
as listed in the readme file but could not find it (the search on the website returned 0 results)
Would it be possible to provide a direct link to the license?

**Comment by cjw85** [comment]
There is a license file within the repository here: https://github.com/nanoporetech/pyguppyclient/blob/master/LICENCE.txt

**Comment by blmt** [comment]
Thanks for the quick reply and for pointing that out.
I still think the link in the Readme file, quoted below, is useless but nevertheless you solved my issue.

"If a copy of the License was not distributed with this file, You can obtain one at http://nanoporetech.com"
