### ISSUE TITLE
Pipelining basecall for chunks from the same read

### ISSUE THREAD

**Issue by harisankarsadasivan** [nanoporetech/pyguppyclient#14]
how to run the pyguppy client on a chunk size of 1000 samples, then concatenate/merge with next 1000 samples etc. I'm testing it offline from a fast5 file.  Or is it that a basecall of a chunk cannot be merged and will be called independently for every consecutive chunks?
Pls guide me.

**Comment by cjw85** [comment]
All requests produce independent results. Further, there is no guarantee that concatenation of the result of two requests will result in an identical sequence to the result of a single request from concatenated inputs.
